import type { Deal } from './deal'

/**
 * Row labels expected in column A, column B holding the value — shared by
 * the Excel importer (app/src/lib/importExcel.ts, generated by
 * app/scripts/generate-mock-xlsx.mjs) and the Google Sheets importer
 * (app/src/lib/googleSheets.ts), which both ultimately parse a simple
 * label/value row layout down to the same Deal shape.
 */
export const DEAL_FIELD_LABELS = {
  name: 'Deal Name',
  propertyType: 'Property Type',
  location: 'Location',
  propertyValue: 'Property Value',
  noi: 'Annual NOI',
  loanRequested: 'Requested Loan Amount',
  amortYears: 'Amortization (Years)',
  ioMonths: 'Interest-Only Period (Months)',
  spreadBps: 'Spread over Index (bps)',
  minDSCR: 'Min DSCR',
  maxLTV: 'Max LTV (%)',
  minDY: 'Min Debt Yield (%)',
} as const

export class DealRowParseError extends Error {}

function toLabelMap(rows: (string | number)[][]): Map<string, string | number> {
  const values = new Map<string, string | number>()
  for (const row of rows) {
    const [label, value] = row
    if (label == null || value == null || value === '') continue
    values.set(String(label).trim(), value)
  }
  return values
}

function requireText(values: Map<string, string | number>, label: string, missing: string[]): string {
  const v = values.get(label)
  if (v === undefined) {
    missing.push(label)
    return ''
  }
  return String(v)
}

function requireNumber(values: Map<string, string | number>, label: string, missing: string[]): number {
  const v = values.get(label)
  if (v === undefined) {
    missing.push(label)
    return 0
  }
  const num = typeof v === 'number' ? v : parseFloat(v)
  if (isNaN(num)) {
    missing.push(`${label} (expected a number, got "${v}")`)
    return 0
  }
  return num
}

/** Maps [label, value] rows (from an Excel sheet or a Sheets API range) into a Deal. */
export function dealFromLabelRows(rows: (string | number)[][], source: Deal['source'], id: string): Deal {
  const values = toLabelMap(rows)
  const missing: string[] = []
  const L = DEAL_FIELD_LABELS

  const name = requireText(values, L.name, missing)
  const propertyType = requireText(values, L.propertyType, missing)
  const location = requireText(values, L.location, missing)
  const propertyValue = requireNumber(values, L.propertyValue, missing)
  const noi = requireNumber(values, L.noi, missing)
  const loanRequested = requireNumber(values, L.loanRequested, missing)
  const amortYears = requireNumber(values, L.amortYears, missing)
  const ioMonths = requireNumber(values, L.ioMonths, missing)
  const spreadBps = requireNumber(values, L.spreadBps, missing)
  const minDSCR = requireNumber(values, L.minDSCR, missing)
  const maxLTV = requireNumber(values, L.maxLTV, missing)
  const minDY = requireNumber(values, L.minDY, missing)

  if (missing.length) {
    throw new DealRowParseError(`Missing or invalid values for: ${missing.join(', ')}.`)
  }

  return {
    id,
    name,
    propertyType,
    location,
    source,
    inputs: { propertyValue, noi, loanRequested, amortYears, ioMonths, spreadBps, minDSCR, maxLTV, minDY },
  }
}
